<?php

/**
 * @file
 * Install, update and uninstall functions for the x402_solana_content module.
 */

use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_install().
 */
function x402_solana_content_install() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_uninstall().
 */
function x402_solana_content_uninstall() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}


